title: Portfolio
author_name : Muhammad Satya Annas
logo: /assets/img/headshot_circle.png
description: Data Enthusiast | Data Scientist | Data Analyst
#show_downloads: true
theme: jekyll-theme-minimal
